// ============================================================================
// decision_tree.dart – Layer 3: ML Classifier (Decision Tree, Improved)
// ============================================================================
import 'dart:convert';
import 'dart:math' as math;
import '../layer1_feature_extraction/feature_extractor.dart';

class DecisionTree {
  final Map<String, dynamic> _root;

  DecisionTree(this._root);

  /// Load tree from the JSON file generated by the Python training script.
  /// The JSON must have the following structure:
  /// {
  ///   "tree": {
  ///     "feature": [...],
  ///     "threshold": [...],
  ///     "children_left": [...],
  ///     "children_right": [...],
  ///     "value": [...],
  ///     "n_node_samples": [...],
  ///     "classes": [...]
  ///   },
  ///   "n_features": 59,
  ///   "n_classes": 4
  /// }
  factory DecisionTree.fromJson(String jsonString) {
    final json = jsonDecode(jsonString) as Map<String, dynamic>;
    final treeData = json['tree'] as Map<String, dynamic>;
    final features = List<int>.from(treeData['feature']);
    final thresholds = List<double>.from(treeData['threshold'].map((x) => (x as num).toDouble()));
    final leftChildren = List<int>.from(treeData['children_left']);
    final rightChildren = List<int>.from(treeData['children_right']);
    final value = treeData['value'] as List;
    // classes is not needed for tree reconstruction; we only use value for distributions
    // final classes = List<int>.from(treeData['classes']); // REMOVED

    // Build the tree recursively starting from node 0
    Map<String, dynamic> buildNode(int nodeIdx) {
      final feat = features[nodeIdx];
      // Leaf node in sklearn tree is indicated by feature == -2
      if (feat == -2) {
        // Leaf: extract class distribution from value[nodeIdx]
        // value is a list of shape (n_nodes, n_classes, 1)
        final nodeValue = value[nodeIdx] as List;
        final classCounts = List<double>.from(nodeValue[0].map((e) => (e as num).toDouble()));
        final total = classCounts.reduce((a, b) => a + b);
        final distribution = classCounts.map((c) => c / total).toList();
        return {'distribution': distribution};
      } else {
        // Internal node
        final threshold = thresholds[nodeIdx];
        final left = buildNode(leftChildren[nodeIdx]);
        final right = buildNode(rightChildren[nodeIdx]);
        return {
          'feature': feat,
          'threshold': threshold,
          'left': left,
          'right': right,
        };
      }
    }

    final root = buildNode(0);
    return DecisionTree(root);
  }

  // --------------------------------------------------------------------------
  // Public API: Predict probability (malicious class)
  // --------------------------------------------------------------------------
  double predictProbability(List<double> features) {
    final node = _traverseToLeaf(_root, features);

    if (node.containsKey('value')) {
      return (node['value'] as num).toDouble();
    } else if (node.containsKey('distribution')) {
      final dist = (node['distribution'] as List)
          .map((e) => (e as num).toDouble())
          .toList();
      if (dist.length <= 1) return 0.0;
      // Assuming class 0 = benign, sum of others = malicious probability
      return dist.sublist(1).reduce((a, b) => a + b);
    } else if (node.containsKey('class')) {
      return (node['class'] as int) == 0 ? 0.0 : 1.0;
    }

    return 0.5; // fallback
  }

  // --------------------------------------------------------------------------
  // Public API: Predict class, confidence, and probability distribution
  // --------------------------------------------------------------------------
  Map<String, dynamic> predictMultiClass(List<double> features) {
    final node = _traverseToLeaf(_root, features);

    List<double> probs = [];
    int cls = 0;
    double maxProb = 0.0;

    if (node.containsKey('distribution')) {
      probs = (node['distribution'] as List)
          .map((e) => (e as num).toDouble())
          .toList();
      maxProb = probs.reduce(math.max);
      cls = probs.indexOf(maxProb);
    } else if (node.containsKey('value')) {
      final prob = (node['value'] as num).toDouble();
      cls = prob > 0.5 ? 1 : 0;
      maxProb = prob > 0.5 ? prob : 1 - prob;
      probs = [1 - prob, prob];
    } else if (node.containsKey('class')) {
      cls = node['class'] as int;
      maxProb = 1.0;
      probs = List.filled(4, 0.0);
      probs[cls] = 1.0;
    } else {
      cls = 0;
      maxProb = 0.5;
      probs = List.filled(4, 0.0);
    }

    String confidence;
    if (maxProb >= 0.8) {
      confidence = 'high';
    } else if (maxProb >= 0.6) {
      confidence = 'medium';
    } else {
      confidence = 'low';
    }

    return {
      'class': cls,
      'confidence': confidence,
      'probabilities': probs,
      'score': maxProb,
    };
  }

  // --------------------------------------------------------------------------
  // Classify URL features (binary: malicious/benign)
  // --------------------------------------------------------------------------
  Map<String, dynamic> classify(UrlFeatures features) {
    final vector = features.toFeatureVector();
    final prob = predictProbability(vector);
    final isMalicious = prob > 0.5;

    String confidence;
    if (prob >= 0.8 || prob <= 0.2) {
      confidence = 'high';
    } else if (prob >= 0.6 || prob <= 0.4) {
      confidence = 'medium';
    } else {
      confidence = 'low';
    }

    return {
      'prediction': isMalicious ? 'malicious' : 'benign',
      'threat_probability': prob,
      'confidence': confidence,
      'score': prob,
    };
  }

  // --------------------------------------------------------------------------
  // Recursive traversal to leaf node
  // --------------------------------------------------------------------------
  Map<String, dynamic> _traverseToLeaf(
      Map<String, dynamic> node, List<double> features) {
    // Leaf nodes have 'distribution' or 'value' or 'class'
    if (node.containsKey('distribution') ||
        node.containsKey('value') ||
        node.containsKey('class')) {
      return node;
    }

    if (!node.containsKey('feature') || !node.containsKey('threshold')) {
      return {'value': 0.5}; // fallback for malformed node
    }

    final featureIndex = node['feature'] as int;
    final threshold = (node['threshold'] as num).toDouble();
    final left = node['left'] as Map<String, dynamic>;
    final right = node['right'] as Map<String, dynamic>;

    return features[featureIndex] <= threshold
        ? _traverseToLeaf(left, features)
        : _traverseToLeaf(right, features);
  }
}