// ============================================================================
// lightgbm.dart – LightGBM Multi-class Classifier (JSON based)
// ============================================================================
import 'dart:convert';
import 'dart:math';

class LightGBMModel {
  final int numClass;
  final List<List<Map<String, dynamic>>> _classTrees;

  LightGBMModel._(this.numClass, this._classTrees);

  /// Load model from JSON file generated by Python training script
  static Future<LightGBMModel> fromJson(String jsonString) async {
    final Map<String, dynamic> root = jsonDecode(jsonString);
    final numClass = root['num_class'] as int;
    final classTreesRaw = root['class_trees'] as List;
    final classTrees = classTreesRaw.map((trees) =>
        List<Map<String, dynamic>>.from(trees.map((t) => t as Map<String, dynamic>))
    ).toList();
    return LightGBMModel._(numClass, classTrees);
  }

  /// Predict class probabilities (softmax)
  List<double> predictProbabilities(List<double> features) {
    final scores = List.filled(numClass, 0.0);
    for (int c = 0; c < numClass; c++) {
      double sum = 0.0;
      for (final tree in _classTrees[c]) {
        sum += _predictTree(tree, features);
      }
      scores[c] = sum;
    }
    // Softmax (numerically stable)
    final maxScore = scores.reduce(max);
    final expScores = scores.map((s) => exp(s - maxScore)).toList();
    final sumExp = expScores.reduce((a, b) => a + b);
    return expScores.map((e) => e / sumExp).toList();
  }

  /// Predict the class index (0..numClass-1)
  int predictClass(List<double> features) {
    final probs = predictProbabilities(features);
    int bestClass = 0;
    double bestProb = probs[0];
    for (int i = 1; i < probs.length; i++) {
      if (probs[i] > bestProb) {
        bestProb = probs[i];
        bestClass = i;
      }
    }
    return bestClass;
  }

  // Recursive tree traversal
  double _predictTree(Map<String, dynamic> node, List<double> features) {
    if (node['leaf'] == true) {
      return (node['value'] as num).toDouble();
    }
    final featureIdx = node['feature'] as int;
    final threshold = (node['threshold'] as num).toDouble();
    if (features[featureIdx] <= threshold) {
      return _predictTree(node['left'] as Map<String, dynamic>, features);
    } else {
      return _predictTree(node['right'] as Map<String, dynamic>, features);
    }
  }
}