// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKOzN5Dmt-ekCr35KfpFdHDwWyryeuXz8',
    appId: '1:1071145926774:android:75d4dccddf6744ebf39f57',
    messagingSenderId: '1071145926774',
    projectId: 'linksentry-84bff',
    databaseURL: 'https://linksentry-84bff-default-rtdb.firebaseio.com',
    storageBucket: 'linksentry-84bff.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjpb-isSbbLqUzwfvEZd4X_FRwyWabm4',
    appId: '1:1071145926774:web:15bef06840ba5fc3f39f57',
    messagingSenderId: '1071145926774',
    projectId: 'linksentry-84bff',
    authDomain: 'linksentry-84bff.firebaseapp.com',
    databaseURL: 'https://linksentry-84bff-default-rtdb.firebaseio.com',
    storageBucket: 'linksentry-84bff.firebasestorage.app',
    measurementId: 'G-C8WSTX0ET2',
  );

}